version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  # todo-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: todo-api
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - PORT=5000
  #     - MONGO_URL=mongodb://mongo:27017/todo-app
  #   networks:
  #     - todo-app-network
  #   depends_on:
  #     - mongo

networks:
  todo-app-network:
    driver: bridge

volumes:
  mongo-data: